### PR TITLE
[Merged by Bors] - Fluvio socket wasm support

### PR DESCRIPTION
**Pull request by simlay**
Co-PR to https://github.com/infinyon/future-aio/pull/70.

The `clone` calls will not be liked by clippy but the websocket connector returns `String` which does not implement `Copy`.

I think the build will fail due to https://github.com/infinyon/future-aio/pull/69.

### CODE REVIEW

**Comment by sehz** [comment]
will merge once https://github.com/infinyon/future-aio/pull/70 is merged  into master

File: src/client/src/sockets.rs [hunk 1]
```diff
@@ -119,8 +119,17 @@ impl ClientConfig {
...
 
     pub(crate) async fn connect(self) -> Result<VersionedSocket, FluvioError> {
+        let addr = self.addr.clone();
+        // When we have websocket proxy in place, this won't be needed.
+        #[cfg(target_arch = "wasm32")]
+        let addr = if addr == "localhost:9010" {
+            String::from("ws://localhost:3001")
+        } else {
+            addr
+        };
```
Comment (simlay) [inline src/client/src/sockets.rs:129]: @sehz Thoughts on what to do in place of this?

File: src/socket/src/sink.rs [hunk 2]
```diff
@@ -210,15 +210,15 @@ impl ExclusiveFlvSink {
...
+        self.fd.clone()
     }
 }
 
 impl Clone for ExclusiveFlvSink {
     fn clone(&self) -> Self {
         Self {
             inner: self.inner.clone(),
-            fd: self.fd,
+            fd: self.fd.clone(),
```
Comment (simlay) [inline src/socket/src/sink.rs:221]: Clippy doesn't like this but it's needed for wasm as the `fd` is a `String` (doesn't implement `Copy`) in wasm32.

File: src/client/src/config/config.rs [hunk 3]
```diff
@@ -15,7 +15,14 @@ use std::fs::create_dir_all;
 use thiserror::Error;
 
 use tracing::debug;
+#[cfg(not(target_arch = "wasm32"))]
 use dirs::home_dir;
+
+#[cfg(target_arch = "wasm32")]
+fn home_dir() -> Option<PathBuf> {
```
Comment (simlay) [inline src/client/src/config/config.rs:22]: This is a work around in place until #1115 is done.

File: src/client/src/sockets.rs (hunk 1 above)
Comment (sehz) [reply src/client/src/sockets.rs:129]: This can passed as addr.  There is no need for hard coding

Comment (simlay) [reply src/client/src/sockets.rs:129]: Yeah, so the reason this is a needed work around is that the client connects to fluvio-sc via a webscocket, then once trying to get a Partition Consumer stream or a producer, the SC gives some metadata about the SPU to connect to which is `localhost:9010` for a local cluster.

This isn't exposed to the client.

When we add a real websocket proxy rather than running `websocat -v --binary ws-l:127.0.0.1:3000 tcp:127.0.0.1:9003`, it needs to do something smarter.

Comment (simlay) [reply src/client/src/sockets.rs]: I removed it from the PR but I'm still using it in my local branch.

File: src/client/Cargo.toml [hunk 4]
```diff
@@ -46,6 +45,9 @@ fluvio-socket = { path = "../socket", version = "0.8.1" }
 fluvio-protocol = { path = "../protocol", version = "0.5.1" }
 dataplane = { version = "0.5.1", path = "../dataplane-protocol", package = "fluvio-dataplane-protocol" }
```
Comment (sehz) [inline src/client/Cargo.toml:47]: need to bump up fluvio-future to use `DefaultDomainConnector`

File: src/client/src/sockets.rs [hunk 5]
```diff
@@ -119,8 +119,8 @@ impl ClientConfig {
     }
 
     pub(crate) async fn connect(self) -> Result<VersionedSocket, FluvioError> {
-        let socket =
-            FluvioSocket::connect_with_connector(&self.addr, self.connector.as_ref()).await?;
+        debug!("Connecting to {:?}", self.addr);
```
Comment (sehz) [inline src/client/src/sockets.rs:122]: use object format:  `debug!( add = %self.addr, "connection to")`

File: src/socket/src/socket.rs [hunk 6]
```diff
@@ -7,8 +7,7 @@ use fluvio_protocol::api::RequestMessage;
 use fluvio_protocol::api::ResponseMessage;
 
 use fluvio_future::net::{
-    BoxReadConnection, BoxWriteConnection, ConnectionFd, DefaultTcpDomainConnector,
-    TcpDomainConnector, TcpStream,
+    BoxReadConnection, BoxWriteConnection, ConnectionFd, DefaultDomainConnector, TcpDomainConnector,
```
Comment (sehz) [inline src/socket/src/socket.rs:10]: TcpDomainConnector should be only imported for Unix?

**Review by sehz — CHANGES_REQUESTED** [review]
Nice work!  Surprised to see Multiplexor works now without code changes.   Few minor nits

**Comment by sehz** [comment]
Doc test fails

File: src/socket/src/socket.rs (hunk 6 above)
Comment (simlay) [reply src/socket/src/socket.rs:10]: I think I forgot to rename this to `SocketDomainConnector` or something in https://github.com/infinyon/future-aio/pull/70. `DefaultConnector is a `Box<dyn TcpDomainConnector>`.

**Comment by sehz** [comment]
Looks good but doc tests seems to failing

**Comment by simlay** [comment]
> Looks good but doc tests seems to failing.

The errors are kinda big but I think it's due to the change in `spawn` from https://github.com/infinyon/future-aio/pull/69

```
 error[E0277]: `dyn TcpDomainConnector` cannot be shared between threads safely
  --> src/spu/src/control_plane/dispatcher.rs:73:9
   |
73 |         spawn(self.dispatch_loop());
   |         ^^^^^ `dyn TcpDomainConnector` cannot be shared between threads safely
   | 
  ::: /mnt/local_disk/actions/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/spawn.rs:28:29
   |
28 |     F: Future<Output = T> + Send + 'static,
   |                             ---- required by this bound in `fluvio_future::task::spawn`
```

**Comment by sehz** [comment]
Hmm. Looks like I screwed up. let me fix this

**Comment by sehz** [comment]
Actually, fluvio master works fine against release version.  So this is caused by: https://github.com/infinyon/future-aio/commit/6409c8ce70e605d51952e6a043b442b6a17e0d52

**Comment by sehz** [comment]
weird. now everything is ok.  try `cargo update` and try running all tests

**Comment by sehz** [comment]
I found elegant way to add conditional constrain to: `TcpDomainConnector`.  Will patch `fluvio-future`

**Comment by sehz** [comment]
done.  this should pass now

**Comment by sehz** [comment]
clippy is failing.  we need to add another trait to `fluvio_future`, something like: 
```
trait CloneConnectionFd {
      fn clone(&self) -> Self;
}

impl CloneConnectionFd  for std::os::unix::io::RawFd {
       fn clone(&self) -> Self {
            self.copy
      }
}

....
```

**Review by sehz — APPROVED** [review]
Finally. nice work
